### PR TITLE
support react 17

### PR DESCRIPTION
**Pull request by parisholley**

### CODE REVIEW

**Comment by parisholley** [comment]
nvm, going to just use a yarnrc entry for now

**Comment by phcerdan** [comment]
Facing incompatibility with react 17.0.1 when trying to install hookstate.

hookstate should be already compatible with react 17, no?

```
╰─ npm install --save @hookstate/core                                                                                                                                               14:28:11 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: X
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from @hookstate/core@3.0.6
npm ERR! node_modules/@hookstate/core
npm ERR!   @hookstate/core@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by avkonst** [comment]
Hi! Hookstate 4 will move to React 17 in the near future. Together with the support for https://github.com/avkonst/hookstate/issues/140

**Comment by avkonst** [comment]
For now, use yarnrc to patch the dependency. Hookstate should work with React 17 already.

**Comment by avkonst** [comment]
In 3.0.6. No other changes done.

**Pull request closed without merging**
