### PR TITLE
Add StateMethodsDestroy to hookstate() typings

### PR DESCRIPTION
**Pull request by speigg**

### CODE REVIEW

**Comment by avkonst** [comment]
Hi, destroy method will get replaced by activate and deactivate methods, because react 18 can resurect unmounted state now. So hookstate will align with react 18. Sorry for hookstate 4 taking longer to roll out, I am extraordinary busy in all fronts of my life at the moment. But I it will come soon.

**Comment by speigg** [comment]
@avkonst nice! We're already using the latest hookstate4 rc, so many great improvements! I love the new subscribable extension. We're still on React v17, but looking to update soon. Will hookstate 4 work with React v17?

**Comment by avkonst** [comment]
Yes

**Comment by avkonst** [comment]
cancelled as Hookstate-4 will have destroyHookstate global function

**Pull request closed without merging**
